version: "3.8"

networks:
  traefik_backend:
    external: true

volumes:
  config:

  downloads:
#    driver: local
#    driver_opts:
#      type: none
#      device: /home/simon/downloads/deluge
#      o: bind

services:
  deluge:
    ## one to the two images or the build:	
    #image: linuxserver/deluge
    #image: calcifernl/docker-deluge-pia
    build: .
    ## Ports accessable for the outside (external port:internal port)
    expose:
      ## HTTP interface 
      - 8112:8112
      ## DHT
      #- 6771:6771
    ## Rights to control VPN tunnels
    cap_add:
      - NET_ADMIN
    ## Access to tunnel 
    devices:
      - /dev/net/tun
    ## Mapping of persistent storage (host:container)
    volumes:
      - config:/config
      - downloads:/downloads
    ## Variables
    environment:
      - TZ=Europe/Amsterdam
      - PUID=33
      - PGID=33
      - UMAKS_SET=007
    ## Enviroment variables with username and password
    ## EDIT this file!
    #env_file:
    #  - secrets/pia.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8112"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s 

    labels:
      ## Reverse proxy
      - traefik.enable=true
      - traefik.http.routers.deluge.entrypoints=websecure
      - traefik.http.routers.deluge.rule=Host("deluge.calcifer.nl")
      - traefik.http.routers.deluge.service=deluge
      - traefik.http.services.deluge.loadbalancer.server.port=8112
